// Code generated by MockGen. DO NOT EDIT.
// Source: cpusage_collector.go

// Package cpumassager is a generated GoMock package.
package cpumassager

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockCPUsageCollector is a mock of CPUsageCollector interface
type MockCPUsageCollector struct {
	ctrl     *gomock.Controller
	recorder *MockCPUsageCollectorMockRecorder
}

// MockCPUsageCollectorMockRecorder is the mock recorder for MockCPUsageCollector
type MockCPUsageCollectorMockRecorder struct {
	mock *MockCPUsageCollector
}

// NewMockCPUsageCollector creates a new mock instance
func NewMockCPUsageCollector(ctrl *gomock.Controller) *MockCPUsageCollector {
	mock := &MockCPUsageCollector{ctrl: ctrl}
	mock.recorder = &MockCPUsageCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCPUsageCollector) EXPECT() *MockCPUsageCollectorMockRecorder {
	return m.recorder
}

// GetCPUsage mocks base method
func (m *MockCPUsageCollector) GetCPUsage() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCPUsage")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetCPUsage indicates an expected call of GetCPUsage
func (mr *MockCPUsageCollectorMockRecorder) GetCPUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCPUsage", reflect.TypeOf((*MockCPUsageCollector)(nil).GetCPUsage))
}
